apiVersion: v1 
kind: Service 
metadata: 
  name: backend 
  namespace: expense 
spec: 
  selector: 
    app: backend
    tier: backend
    project: expense 
    version: green
  ports: 
  - protocol: TCP 
    port: 8080 
    targetPort: 8080